### ISSUE TITLE
getting error.

### ISSUE THREAD

**Issue by guddukhan1987** [theSage21/BookRead#1]
File "./bkrd", line 114
    print(clear, end='\r')
                    ^
SyntaxError: invalid syntax

**Comment by theSage21** [comment]
This would be due to the fact that your Operating System has `Python 2.7` as a default. It can be easily fixed by:  
1. Open the `bkrd` file in a text editor
2. Go to line number 114
3. replace with `print clear, '\r',` **Note comma at the end**

Or you could install `Python3` on your computer (`sudo apt-get install python3` for Ubuntu) and replace the first line with `#! /usr/bin/python3`
